#!/bin/bash
	                                                    


echo -e "
############ GITHUB DORK SCANNER ############
###########  coded by interneturtle   ############
#############################################
"
echo -e " password "
echo " https://github.com/search?q=%22$1%22+password&type=Code "
echo -e " \ndockercfg "
echo " https://github.com/search?q=%22$1%22+dockercfg&type=Code "
echo -e " \npem private "
echo " https://github.com/search?q=%22$1%22+pem%20private&type=Code "
echo -e " \nid_rsa "
echo " https://github.com/search?q=%22$1%22+id_rsa&type=Code "
echo -e " \naws_access_key_id "
echo " https://github.com/search?q=%22$1%22+aws_access_key_id&type=Code "
echo -e " \ns3cfg "
echo " https://github.com/search?q=%22$1%22+s3cfg&type=Code "
echo -e " \nhtpasswd " 
echo " https://github.com/search?q=%22$1%22+htpasswd&type=Code "
echo -e " \ngit-credentials "
echo " https://github.com/search?q=%22$1%22+git-credentials&type=Code "
echo -e " \nbashrc password "
echo " https://github.com/search?q=%22$1%22+bashrc%20password&type=Code "
echo -e " \nxoxp OR xoxb OR xoxa "
echo " https://github.com/search?q=%22$1%22+xoxp%20OR%20xoxb%20OR%20xoxa&type=Code "
echo -e " \nSECRET_KEY "
echo " https://github.com/search?q=%22$1%22+SECRET_KEY&type=Code "
echo -e " \nclient_secret "
echo " https://github.com/search?q=%22$1%22+client_secret&type=Code "
echo -e " \nsshd_confg "
echo " https://github.com/search?q=%22$1%22+sshd_config&type=Code "
echo -e " \ngithub_token "
echo " https://github.com/search?q=%22$1%22+github_token&type=Code "
echo -e " \napi_key "
echo " https://github.com/search?q=%22$1%22+api_key&type=Code " 
echo -e " \nFTP "
echo " https://github.com/search?q=%22$1%22+FTP&type=Code "
echo -e " \napp_secret "
echo " https://github.com/search?q=%22$1%22+app_secret&type=Code "
echo -e " \npasswd "
echo " https://github.com/search?q=%22$1%22+passwd&type=Code "
echo -e " \ns3.yml "
echo " https://github.com/search?q=%22$1%22+.env&type=Code "
echo -e " \n.exs "
echo " https://github.com/search?q=%22$1%22+.exs&type=Code "
echo -e " \nbeanstalkd.yml "
echo " https://github.com/search?q=%22$1%22+beanstalkd.yml&type=Code "
echo -e " \ndeploy.rake "
echo " https://github.com/search?q=%22$1%22+deploy.rake&type=Code "
echo -e " \nmysql "
echo " https://github.com/search?q=%22$1%22+mysql&type=Code "
echo -e " \ncredentials "
echo " https://github.com/search?q=%22$1%22+credentials&type=Code "
echo -e " \nPWD "
echo " https://github.com/search?q=%22$1%22+PWD&type=Code "
echo -e " \ndeploy.rake "
echo " https://github.com/search?q=%22$1%22+deploy.rake&type=Code "
echo -e " \nbash_history "
echo " https://github.com/search?q=%22$1%22+.bash_history&type=Code "
echo -e " \n.sls "
echo " https://github.com/search?q=%22$1%22+.sls&type=Code "
echo -e " \nsecrets "
echo " https://github.com/search?q=%22$1%22+secrets&type=Code "
echo -e " \ncomposer.json "
echo " https://github.com/search?q=%22$1%22+composer.json&type=Code "
echo -e "#################################################################### "
echo -e "FINISHED IT "
